### ISSUE TITLE
2FA invalid barcode

### ISSUE THREAD

**Issue by shangzhou** [blocktrail/blocktrail-webwallet#13]
After scan the QRCode "invalid barcode" poped up, but manually enter is working.

**Comment by afk11** [comment]
What app were you using at the time?

**Comment by shangzhou** [comment]
Google Authenticator.

**Comment by shangzhou** [comment]
Any update here?

**Comment by rubensayshi** [comment]
@shangzhou have you tried any other 2FA scans with google auth recently?

**Comment by shangzhou** [comment]
@rubensayshi just tried with google auth same issue.

**Comment by rubensayshi** [comment]
@shangzhou I found the problem, on iOS it doesn't allow spaces in the name of the "issuer", fixed it (server side fix) and it should be working now!

**Comment by shangzhou** [comment]
Thanks for fixing.
