### ISSUE TITLE
Invalid recaptcha error

### ISSUE THREAD

**Issue by diegomr86** [blocktrail/blocktrail-webwallet#139]
Trying to run the blocktrail webwallet on my server aways returns a "invalid recaptcha" error:
{"code":401,"msg":"invalid recaptcha"}
I followed the README instructions and everything compiled and run ok except this error.

**Comment by jiangjinyuan** [comment]
I think you need to check your configuration about "GOOGLE_RECAPTCHA_SITE_KEY"

**Comment by jiangjinyuan** [comment]
If there are no other problems, I will close this issue. @diegomr86
