### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by slick2** [blocktrail/blocktrail-webwallet#19]
@afk11 instructions on the README.md 

```
npm install -g gulp
git clone https://github.com/blocktrail/blocktrail-webwallet.git
cd  blocktrail-webwallet
npm install
git submodule update --init --recursive # for translations package
cp appconfig.example.json appconfig.json
gulp
```

**Comment by slick2** [comment]
also please include the minimum node.js version to run, i've tried node version 0.10 upto 4.0, i've got it working on 7.0

**Comment by afk11** [comment]
I'll update the readme with that, thanks! I'll have to look at the minimum, I usually use v0.12.15 or so, but  worth mentioning.
