### ISSUE TITLE
Unable to create Wallet

### ISSUE THREAD

**Issue by suneelkumar91** [blocktrail/blocktrail-webwallet#80]
Error: Origin is not allowed by Access-Control-Allow-Origin 

![screenshot from 2018-01-16 17-11-02](https://user-images.githubusercontent.com/5219123/34988359-5eebeb78-fae0-11e7-8a58-5959c4825cd5.png)

Kindly help me out from this issue ASAP!!

**Comment by flezy4** [comment]
please I am looking for how to buy a Bitcoin from legit businesses operator

**Comment by jiangjinyuan** [comment]
> Error: Origin is not allowed by Access-Control-Allow-Origin
> 
> ![screenshot from 2018-01-16 17-11-02](https://user-images.githubusercontent.com/5219123/34988359-5eebeb78-fae0-11e7-8a58-5959c4825cd5.png)
> 
> Kindly help me out from this issue ASAP!!

@suneelkumar91 Maybe you can try to add this in your local "appconfig.json" file:
`"API_HOST": "wallet-api.btc.com",`

**Comment by jiangjinyuan** [comment]
I close the issue now, if the problem still exists, I will reopen again!
